services:
  - type: web
    name: ai-tool-backend
    runtime: python
    region: oregon
    plan: free
    branch: Backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python3 -m uvicorn backend_api.master_backend_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false
      - key: MASTER_API_KEY
        sync: false
    autoDeploy: true
