services:
  - type: web
    name: fastapi-backend
    env: python
    region: oregon
    plan: free
    branch: Backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn backend_api.master_backend_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: OPENAI_API_KEY
        sync: false
      - key: MASTER_API_KEY
        sync: false
    autoDeploy: true
